"""Full chain without downloads or a GPU: synthetic clips + the native encoder.

    python examples/native_end_to_end.py --out E:/work/wpm_run/native_demo

Trains a tiny world model, resumes it in a fresh process, evaluates against the three
baselines, trains the optional RGB decoder against the frozen world latents, then runs
a streaming demo and a state-only query -- both with and without decoded keyframes.
Input is synthetic video generated by this script and the native encoder is randomly
initialized, so the example needs no downloads and no GPU.

Run artifacts are written to ``--out``; the synthetic clips and their token cache
live in an OS temporary directory, so nothing is created inside the package.
``--out/config.json`` therefore records those temporary paths:
reuse it to see the shape of a real configuration, or point ``data.video_dir`` and
``data.cache_dir`` at your own clips before running the CLI on it.
"""

import argparse
import json
from pathlib import Path
import subprocess
import sys
import tempfile

import torch

from wpm_video import (DataConfig, DecoderConfig, DecoderTrainConfig, EncoderConfig, ModelConfig,
                       NativeEncoder, RunConfig, TokenDataset, TrainConfig, VideoWorldModel,
                       baseline_summary, build_model, cache_video_tokens, compare, demo,
                       evaluate_baselines, evaluate_model, fit_baseline_stats, fit_projection,
                       load_decoder, query_saved_state, run_decoder_training, train)

FRAMES, SIZE, FPS = 16, 64, 8.0


def write_clip(path: Path, seed: int = 0) -> Path:
    """A tiny synthetic mp4 whose content moves in space and time."""
    import cv2
    import numpy as np
    generator = np.random.default_rng(seed)
    path.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(str(path), cv2.VideoWriter_fourcc(*"mp4v"), FPS, (SIZE, SIZE))
    for index in range(FRAMES):
        frame = np.zeros((SIZE, SIZE, 3), np.uint8)
        offset = int((SIZE - 20) * (index / (FRAMES - 1)))
        frame[10:30, offset:offset + 20] = (200, 40, 40)
        frame[40:60, 40 - offset // 3:60 - offset // 3] = (40, 40, 200)
        frame = np.clip(frame.astype(np.int16) + generator.integers(0, 12, frame.shape), 0, 255)
        writer.write(frame.astype(np.uint8))
    writer.release()
    return path


def make_clips(directory: Path, count: int = 3) -> list:
    return [write_clip(directory / f"clip{index}.mp4", seed=index) for index in range(count)]


def native_encoder(d_model: int = 48, seed: int = 5):
    return NativeEncoder(d_model=d_model, image_size=SIZE, patch=16, tubelet=2, seed=seed)


def tiny_config(train_videos, val_videos, steps: int = 6, decoder_steps: int = 60,
                seed: int = 0) -> RunConfig:
    """World model plus a deliberately small decoder so the CPU example stays quick.

    The shipped default decoder is larger (``DecoderConfig()``: 128 pixel output,
    1.5M parameters); this one reuses the 64 pixel clips so the example runs in
    seconds. Either way the decoder is optional: the world model does not use it.
    """
    return RunConfig(
        name="native_demo",
        data=DataConfig(fps=FPS, chunk_frames=4, chunk_stride_frames=4, image_size=SIZE,
                        context_chunks=2, window_stride_chunks=1, horizon_chunks=[1],
                        max_horizon_chunks=2, train_videos=train_videos, val_videos=val_videos),
        encoder=EncoderConfig(kind="native", device="cpu", batch_clips=2),
        model=ModelConfig(d_world=32, d_hidden=64, slots=16, heads=4, substep_seconds=0.125,
                          max_substeps=64, anchor_bandwidth=1.0),
        train=TrainConfig(seed=seed, batch_windows=2, max_steps=steps, eval_interval=3,
                          eval_batches=1, device="cpu", log_interval=1, max_wall_seconds=600.0),
        decoder=DecoderConfig(image_size=SIZE, base_channels=16, channel_multipliers=[1, 2],
                              stem_blocks=1, blocks_per_stage=1),
        decoder_train=DecoderTrainConfig(seed=seed, batch_windows=2, learning_rate=2e-3,
                                         max_steps=decoder_steps, eval_interval=20, eval_batches=1,
                                         log_interval=5, max_wall_seconds=600.0,
                                         frame_cache_videos=2),
    )


CHILD = """
import json, sys
from pathlib import Path
import torch
from wpm_video import NativeEncoder, RunConfig, TokenDataset, build_model, fit_projection, train
payload = json.loads(sys.argv[1])
config = RunConfig.load(Path(payload["config_path"]))
train_set = TokenDataset(config.data, Path(payload["cache_dir"]), config.encoder, "train")
val_set = TokenDataset(config.data, Path(payload["cache_dir"]), config.encoder, "val")
torch.manual_seed(0)
encoder = NativeEncoder(d_model=48, image_size=64, patch=16, tubelet=2, seed=5)
model = build_model(config, encoder, torch.device("cpu"))
fit_projection(model, train_set)
train(config, model, train_set, val_set, Path(payload["out"]), torch.device("cpu"),
      resume=payload["resume"], provenance={"splits": payload["splits"]})
print("resume ok")
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=Path("runs/native_demo"),
                        help="output directory (create it outside the package)")
    parser.add_argument("--steps", type=int, default=40, help="world model training steps")
    parser.add_argument("--decoder-steps", type=int, default=60, help="decoder training steps")
    args = parser.parse_args()
    out = args.out
    out.mkdir(parents=True, exist_ok=True)
    work = Path(tempfile.mkdtemp(prefix="wvm_native_"))
    video_dir = work / "videos"
    names = [path.stem for path in make_clips(video_dir, 3)]
    config = tiny_config(names[:2], names[2:], steps=args.steps,
                         decoder_steps=args.decoder_steps)
    # the decoder reads its RGB targets from the source clips and its latents from the
    # token cache, so both locations must be the ones this run actually used
    config.data.video_dir = str(video_dir)
    config.data.cache_dir = str(work / "cache")
    config.save(out / "config.json")

    encoder = native_encoder()
    for name in names:
        cache_video_tokens(video_dir / f"{name}.mp4", config.data, encoder, work / "cache",
                           batch_clips=2)
    print(f"cached {len(names)} synthetic clips")

    torch.manual_seed(0)
    model = build_model(config, encoder, torch.device("cpu"))
    train_set = TokenDataset(config.data, work / "cache", config.encoder, "train")
    val_set = TokenDataset(config.data, work / "cache", config.encoder, "val")
    fit_projection(model, train_set)
    summary = train(config, model, train_set, val_set, out / "train", torch.device("cpu"),
                    provenance={"splits": {"train": names[:2], "val": names[2:]}})
    print(f"trained {summary['steps']} steps, best val NLL "
          f"{summary['best']['val_mean_nll_bits_per_dim']:.4f}")

    payload = {"config_path": str(out / "config.json"), "cache_dir": str(work / "cache"),
               "resume": str(out / "train" / "final.pt"), "out": str(out / "train_resumed"),
               "splits": {"train": names[:2], "val": names[2:]}}
    result = subprocess.run([sys.executable, "-c", CHILD, json.dumps(payload)],
                            capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"resume demo failed:\n{result.stderr[-1500:]}")
    print("fresh-process resume:", result.stdout.strip().splitlines()[-1])

    model, _ = VideoWorldModel.from_checkpoint(out / "train" / "final.pt")
    metrics = evaluate_model(model, val_set, config, torch.device("cpu"), 2)
    stats = fit_baseline_stats(model, train_set, config, torch.device("cpu"), 2)
    baselines = evaluate_baselines(model, val_set, config, torch.device("cpu"), 2, stats)
    table = compare(metrics, baselines, config)
    (out / "eval.json").write_text(json.dumps({"model": metrics, "baselines": baselines,
                                               "comparison": table}, indent=2, default=float),
                                   encoding="utf-8")
    print("baselines:", json.dumps(baseline_summary(baselines), indent=2, default=float))

    demo_result = demo(model, encoder, config, video_dir / f"{names[2]}.mp4", torch.device("cpu"),
                       out / "predict", prefix_chunks=2, horizons=[1])
    print("demo horizons:", json.dumps(demo_result["summary"]["horizons"], default=float))
    queried = query_saved_state(model, out / "predict" / "world_state.pt", [1.0, 4.0],
                                torch.device("cpu"), out / "query")
    print("state-only query:", json.dumps(queried["summary"]["queries"], indent=2, default=float))

    # --- optional RGB decoder -------------------------------------------------
    # Trained separately against the *frozen* world checkpoint: the same latents the
    # demo above predicts in, so a predicted mu can be decoded later. The world model,
    # the encoder and the projection are not touched.
    decoder_summary = run_decoder_training(config, out / "train" / "final.pt",
                                           out / "decoder", torch.device("cpu"))
    held_out = decoder_summary["final_val"]
    print(f"decoder: {decoder_summary['decoder']['parameters']:,} parameters, "
          f"{decoder_summary['steps']} steps, held-out l1={held_out['l1']:.4f} "
          f"mse={held_out['mse']:.5f} psnr={held_out['psnr_db']:.2f}dB "
          f"(constant-frame reference l1={held_out['constant_frame_reference']['l1']:.4f})")

    decoder, decoder_payload = load_decoder(out / "decoder" / "final.pt")
    decoded_demo = demo(model, encoder, config, video_dir / f"{names[2]}.mp4", torch.device("cpu"),
                        out / "predict_decoded", prefix_chunks=2, horizons=[1],
                        decoder=decoder, decoder_payload=decoder_payload)
    keyframes = decoded_demo["summary"]["decoded_rgb"]["predicted_keyframes"]
    print("decoded keyframes:", json.dumps(keyframes, indent=2, default=float))

    decoded_query = query_saved_state(model, out / "predict_decoded" / "world_state.pt",
                                      [1.0, 2.0], torch.device("cpu"), out / "query_decoded",
                                      decoder=decoder, decoder_payload=decoder_payload,
                                      config=config)
    print("decoded state-only query:",
          json.dumps(decoded_query["summary"]["decoded_rgb"]["keyframes"], indent=2, default=float))

    print(f"artifacts under {out}: world state and latent artifacts, "
          "decoded_*.png keyframes (one per horizon, not a continuous video) and "
          "target_reconstruction_*.png for the decoder-only view")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
